### ISSUE TITLE
ghcr.io anonymous authentication is broken.

### ISSUE THREAD

**Issue by thesayyn** [bazel-contrib/rules_oci#193]
it requires GITHUB_TOKEN to be sent in WWW-Authenticate exchange.

**Comment by kormide** [comment]
Note that for GitHub Actions, an `oci_push` will work after authenticating with docker using the `docker/login-action` action like so:

```yaml
      - name: docker login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```
